### ISSUE TITLE
Wavelet preprocessing leakage

### ISSUE THREAD

**Issue by q-learning-trader** [huddyyeo/soft-attention_LSTM_forecasting#1]
Hi @huddyyeo,

Interesting work, thanks for sharing.
Unfortunately this paper contains a major issue.
Applying wavelet denoising one-shot to all dataset before training imply that you assume to know the future values before doing that. Basically the wavelet transform uses future values to better denoise the financial time series. This is something many paper use and it could never happen in reality.
The correct way to apply wavelet transform is taking a sliding window of samples.
Do you agree? It would be interesting to get your feedback.
Thanks.

**Comment by huddyyeo** [comment]
Hi Q-learning trader! Thanks for your feedback.
Yes, I'm agreeable with your view that the wavelet denoising might have this drawback, which is why I haven't implemented it yet! The wavelet transform is still new to me so I held off implementing it in the model as I don't fully understand it yet. I'll be conducting a bit more research before adding it in but thank you so much for your feedback! :)
Thanks!

**Comment by q-learning-trader** [comment]
@huddyyeo the only way you can use wavelet is with sliding window. In the sense that at each timestep t, you can only access T samples (T is your sliding window) and apply wavelet transform to x(t-T), x(t-T+1),x(t-T+2), ...., x(t) and you get a denoised version of your input.
But apart this, I have tried to run your code against 5180 samples dataset and I think it is not working. It is basically delaying the input time series. It is not learning, apparently:

![image](https://user-images.githubusercontent.com/60422638/74603865-6c55fa80-50b8-11ea-8562-17d82e28d983.png)

I need to study the code and I can't tell you where the problem is.
Did you notice that?

**Comment by huddyyeo** [comment]
Yes I am aware of both matters. I have put a disclaimer in the readme that the project is a Work in progress and it is **not completed yet**. The model is currently optimizing the errors by simply predicting a 0 in all cases. There are several reasons why this occurs, eg size of network and architecture. The paper I am using does not specify the size of the network, regularisation techniques or activation functions they are using hence I am still in the midst of tuning the model.
